### ISSUE TITLE
Add official support for pre-commit.com (python tool)

### ISSUE THREAD

**Issue by fregante** [keithamus/sort-package-json#354]
See https://pre-commit.com

I think it's a matter of specifying a `.pre-commit-hooks.yaml` file in the root of the repo, then it becomes available as:

```yaml

  - repo: https://github.com/keithamus/sort-package-json
    rev: v3.0.0
    hooks:
      - id: sort-package-json
```

See https://pre-commit.com/hooks.html for existing hooks or see Biome's setup for example: https://github.com/biomejs/pre-commit/blob/main/.pre-commit-hooks.yaml
